{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.luxgroup",
    "module": "kotrace",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotrace-0.1.0.jar",
          "url": "kotrace-0.1.0.jar",
          "size": 26789,
          "sha512": "c94f72df7f9dd5564acb9a514f613116dec243e21c65306627c85b1fdb424de06dbbc3b8e5fe83280894c022e471d783c07a7958e2d92165b46c27ba1d5ecca8",
          "sha256": "685388dc6934a2e679e08fda6f47632981720eb0eb6a9f5e1bae8f14fcd7d746",
          "sha1": "19d5022729eec3064f4099100c0f958079f20541",
          "md5": "650af316606ea2f1fd6447a17169a9c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotrace-0.1.0.jar",
          "url": "kotrace-0.1.0.jar",
          "size": 26789,
          "sha512": "c94f72df7f9dd5564acb9a514f613116dec243e21c65306627c85b1fdb424de06dbbc3b8e5fe83280894c022e471d783c07a7958e2d92165b46c27ba1d5ecca8",
          "sha256": "685388dc6934a2e679e08fda6f47632981720eb0eb6a9f5e1bae8f14fcd7d746",
          "sha1": "19d5022729eec3064f4099100c0f958079f20541",
          "md5": "650af316606ea2f1fd6447a17169a9c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotrace-0.1.0-sources.jar",
          "url": "kotrace-0.1.0-sources.jar",
          "size": 6040,
          "sha512": "9f9903ee2b9e5d4fc12cfd5f33ae013f3ea2cedf214ff7932303ae1c632ee97344e24586969c7c9fb07db4a6085757be307dba3e1a9fe53e4c2dddf6d6605ad9",
          "sha256": "d782721d34d14ffb4bea4a142cb6574cd4236828f3f0fc3de01030f547aa1a7b",
          "sha1": "efdbb57a05eaba31848830dcb26c93674598f530",
          "md5": "1ef83651d1f4fd673d194877544f0e83"
        }
      ]
    }
  ]
}
